# Generated by Django 4.2 on 2023-04-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_dept', models.IntegerField(blank=True, null=True)),
                ('emp_idno', models.IntegerField(blank=True, null=True)),
                ('rnk2', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'abc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('act_fname', models.CharField(blank=True, max_length=20, null=True)),
                ('act_lname', models.CharField(blank=True, max_length=20, null=True)),
                ('act_gender', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actorsbackup2017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_fname', models.CharField(blank=True, max_length=20, null=True)),
                ('act_lname', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'actorsbackup2017',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ahmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('department_id', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'ahmed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('start_dt_time', models.DateTimeField()),
                ('end_dt_time', models.DateTimeField()),
                ('examinationroom', models.TextField()),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsstRefereeMast',
            fields=[
                ('ass_ref_id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('ass_ref_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'asst_referee_mast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
                ('process', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'bh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_no', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('purch_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ord_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'blah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('blockfloor', models.IntegerField(primary_key=True, serialize=False)),
                ('blockcode', models.IntegerField()),
            ],
            options={
                'db_table': 'block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('salesman_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'c',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('pricerange', models.DecimalField(decimal_places=0, max_digits=6)),
                ('events', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=40)),
                ('casino', models.CharField(max_length=75, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'casino',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoachMast',
            fields=[
                ('coach_id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('coach_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'coach_mast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Col1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_column_field', models.IntegerField(blank=True, db_column='?column?', null=True)),
            ],
            options={
                'db_table': 'col1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyMast',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'company_mast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(blank=True, max_length=2, null=True)),
                ('country_name', models.CharField(blank=True, max_length=40, null=True)),
                ('region_id', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'customer_backup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customerdemographics',
            fields=[
                ('customertypeid', models.CharField(primary_key=True, serialize=False)),
                ('customerdesc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customerdemographics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_no', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('purch_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ord_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'customer_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerId123',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_no', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('purch_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ord_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'customer_id_123',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.CharField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=40)),
                ('contactname', models.CharField(blank=True, max_length=30, null=True)),
                ('contacttitle', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('fax', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customersbackup2017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('employee_id', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rnk', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customersbackup2017',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('department_id', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('department_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'department_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('field_column_field', models.IntegerField(blank=True, db_column='?column?', null=True)),
            ],
            options={
                'db_table': 'department_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
                ('manager_id', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('location_id', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('dir_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dir_fname', models.CharField(blank=True, max_length=20, null=True)),
                ('dir_lname', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Duplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'duplicate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elephants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elephants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('ename', models.CharField(blank=True, max_length=13, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('eid', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'emp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpDepartment',
            fields=[
                ('dpt_code', models.IntegerField(primary_key=True, serialize=False)),
                ('dpt_name', models.CharField(max_length=15)),
                ('dpt_allotment', models.IntegerField()),
            ],
            options={
                'db_table': 'emp_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('emp_idno', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_fname', models.CharField(max_length=15)),
                ('emp_lname', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'emp_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField(blank=True, null=True)),
                ('ename', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('titleofcourtesy', models.CharField(blank=True, max_length=25, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('homephone', models.CharField(blank=True, max_length=24, null=True)),
                ('extension', models.CharField(blank=True, max_length=4, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photopath', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeescopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('job_id', models.CharField(blank=True, max_length=10, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('commission_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('manager_id', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('department_id', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'employeescopy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=25, null=True)),
                ('winner', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'ff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('avg', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'fg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameScores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('gen_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gen_title', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoalDetails',
            fields=[
                ('goal_id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('goal_time', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('goal_type', models.CharField(max_length=1)),
                ('play_stage', models.CharField(max_length=1)),
                ('goal_schedule', models.CharField(max_length=2)),
                ('goal_half', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'goal_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('grade_1', models.IntegerField(blank=True, null=True)),
                ('grade_2', models.IntegerField(blank=True, null=True)),
                ('grade_3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_one', models.IntegerField(blank=True, null=True)),
                ('number_two', models.IntegerField(blank=True, null=True)),
                ('number_three', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hello',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hello11122',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hello1_1122',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hello112',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hello1_12',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hello12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hello_12',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(blank=True, max_length=20, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(blank=True, max_length=20, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'item_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMast',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=25)),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'item_mast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobGrades',
            fields=[
                ('grade_level', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lowest_sal', models.DecimalField(decimal_places=0, max_digits=5)),
                ('highest_sal', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
            options={
                'db_table': 'job_grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('employee_id', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_id', models.CharField(max_length=10)),
                ('department_id', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'job_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=35)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'kk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kkk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'kkk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('street_address', models.CharField(blank=True, max_length=40, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state_province', models.CharField(blank=True, max_length=25, null=True)),
                ('country_id', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Londoncustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'londoncustomers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'manufacturers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_idno', models.IntegerField(blank=True, null=True)),
                ('emp_fname', models.CharField(blank=True, max_length=15, null=True)),
                ('emp_lname', models.CharField(blank=True, max_length=15, null=True)),
                ('emp_dept', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatchCaptain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'match_captain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_stage', models.CharField(max_length=1)),
                ('win_lose', models.CharField(max_length=1)),
                ('decided_by', models.CharField(max_length=1)),
                ('goal_score', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('penalty_score', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'match_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatchMast',
            fields=[
                ('match_no', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('play_stage', models.CharField(max_length=1)),
                ('play_date', models.DateField()),
                ('results', models.CharField(max_length=5)),
                ('decided_by', models.CharField(max_length=1)),
                ('goal_score', models.CharField(max_length=5)),
                ('audence', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('stop1_sec', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('stop2_sec', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'match_mast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maxim00',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'maxim00',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maximum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'maximum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maximum00',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'maximum00',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maximum899',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'maximum899',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('brand', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'medication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ord_date', models.DateField(blank=True, null=True)),
                ('namemax', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'meow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mov_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mov_title', models.CharField(blank=True, max_length=50, null=True)),
                ('mov_year', models.IntegerField(blank=True, null=True)),
                ('mov_time', models.IntegerField(blank=True, null=True)),
                ('mov_lang', models.CharField(blank=True, max_length=15, null=True)),
                ('mov_dt_rel', models.DateField(blank=True, null=True)),
                ('mov_rel_country', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'movie_cast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='My',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('avg', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'my',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mytemptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('avg', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'mytemptable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mytest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.DecimalField(decimal_places=0, max_digits=6, unique=True)),
                ('ord_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ord_date', models.DateField()),
                ('cust_code', models.CharField(max_length=6)),
                ('agent_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'mytest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mytest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.DecimalField(decimal_places=0, max_digits=6, unique=True)),
                ('ord_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ord_date', models.DateField()),
                ('cust_code', models.CharField(max_length=6)),
                ('agent_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'mytest1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='New123',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, db_column='Customer', max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('salesman', models.CharField(blank=True, db_column='Salesman', max_length=30, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'new123',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Newsalesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'newsalesman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Newtab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_no', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('purch_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ord_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'newtab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'new_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Newtable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.IntegerField(blank=True, null=True)),
                ('roomtype', models.CharField(blank=True, max_length=30, null=True)),
                ('blockfloor', models.IntegerField(blank=True, null=True)),
                ('blockcode', models.IntegerField(blank=True, null=True)),
                ('unavailable', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'newtable2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NobelWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=25, null=True)),
                ('winner', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'nobel_win',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno', models.IntegerField(blank=True, null=True)),
                ('dos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'nuevo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField(blank=True, null=True)),
                ('two', models.IntegerField(blank=True, null=True)),
                ('three', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'numbers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Numeri',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('decimali', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'numeri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Numeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno', models.IntegerField(blank=True, null=True)),
                ('dos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'numeros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('employeeid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('registered', models.BooleanField()),
                ('ssn', models.IntegerField()),
            ],
            options={
                'db_table': 'nurse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('avg', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'oi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField(blank=True, null=True)),
                ('requireddate', models.DateField(blank=True, null=True)),
                ('shippeddate', models.DateField(blank=True, null=True)),
                ('freight', models.FloatField(blank=True, null=True)),
                ('shipname', models.CharField(blank=True, max_length=40, null=True)),
                ('shipaddress', models.CharField(blank=True, max_length=60, null=True)),
                ('shipcity', models.CharField(blank=True, max_length=15, null=True)),
                ('shipregion', models.CharField(blank=True, max_length=15, null=True)),
                ('shippostalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('shipcountry', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_no', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('purch_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ord_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'orders2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orozco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'orozco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.DecimalField(decimal_places=0, max_digits=6, unique=True)),
                ('ord_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ord_date', models.DateField()),
                ('cust_code', models.CharField(max_length=6)),
                ('agent_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'partest1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField()),
                ('part_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField()),
                ('part_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('insuranceid', models.IntegerField()),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenaltyGk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'penalty_gk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenaltyShootout',
            fields=[
                ('kick_id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('score_goal', models.CharField(max_length=1)),
                ('kick_no', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'penalty_shootout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personid', models.IntegerField(blank=True, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'persons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('employeeid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('ssn', models.IntegerField()),
            ],
            options={
                'db_table': 'physician',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('sent_off', models.CharField(blank=True, max_length=1, null=True)),
                ('play_schedule', models.CharField(max_length=2)),
                ('play_half', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'player_booked',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_out', models.CharField(max_length=1)),
                ('time_in_out', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('play_schedule', models.CharField(max_length=2)),
                ('play_half', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'player_in_out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerMast',
            fields=[
                ('player_id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('jersey_no', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('player_name', models.CharField(max_length=40)),
                ('dt_of_bir', models.DateField(blank=True, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('playing_club', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'player_mast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayingPosition',
            fields=[
                ('position_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('position_desc', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'playing_position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('cost', models.FloatField()),
            ],
            options={
                'db_table': 'procedure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=40)),
                ('quantityperunit', models.CharField(blank=True, max_length=20, null=True)),
                ('unitprice', models.FloatField(blank=True, null=True)),
                ('unitsinstock', models.SmallIntegerField(blank=True, null=True)),
                ('unitsonorder', models.SmallIntegerField(blank=True, null=True)),
                ('reorderlevel', models.SmallIntegerField(blank=True, null=True)),
                ('discontinued', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramyasales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'ramyasales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_stars', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('num_o_ratings', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefereeMast',
            fields=[
                ('referee_id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('referee_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'referee_mast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('regiondescription', models.CharField()),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('region_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'related',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('rev_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rev_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'reviewer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('roomtype', models.CharField(max_length=30)),
                ('blockcode', models.IntegerField()),
                ('unavailable', models.BooleanField()),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_no', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('purch_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ord_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'rt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('salesman_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'salesman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesman2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'salesman2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesmanDo1304',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('commission', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'salesman_do1304',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('commission', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sample_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('shipperid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'shippers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoccerCity',
            fields=[
                ('city_id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'soccer_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoccerCountry',
            fields=[
                ('country_id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('country_abbr', models.CharField(max_length=4)),
                ('country_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'soccer_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoccerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_group', models.CharField(max_length=1)),
                ('match_played', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('won', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('draw', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('lost', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('goal_for', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('goal_agnst', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('goal_diff', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('points', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('group_position', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'soccer_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoccerVenue',
            fields=[
                ('venue_id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=30)),
                ('aud_capacity', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'soccer_venue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('stayid', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'stay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'string',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplierid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=40)),
                ('contactname', models.CharField(blank=True, max_length=30, null=True)),
                ('contacttitle', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('fax', models.CharField(blank=True, max_length=24, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sybba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.DecimalField(decimal_places=0, max_digits=6, unique=True)),
                ('ord_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ord_date', models.DateField()),
                ('cust_code', models.CharField(max_length=6)),
                ('agent_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'sybba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 't1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tab2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tab2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, db_column='Customer Name', max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('salesman', models.CharField(blank=True, db_column='Salesman', max_length=30, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'table1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamCoaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'team_coaches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tempa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tempa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'temp_array',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tempcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tempcustomer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temphi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'temphi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tempp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tempp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tempp11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tempp11',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_id', models.IntegerField(blank=True, null=True)),
                ('rev_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'temp_reviewer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tempsalesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tempsalesman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempSamesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'temp_samesman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'temp_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('territoryid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('territorydescription', models.CharField()),
            ],
            options={
                'db_table': 'territories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teste',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'testtable',
                'db_table_comment': 'a temporary table for some queries ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeri', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usstates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateid', models.SmallIntegerField()),
                ('statename', models.CharField(blank=True, max_length=100, null=True)),
                ('stateabbr', models.CharField(blank=True, max_length=2, null=True)),
                ('stateregion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'usstates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True)),
                ('substring', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vowl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zebras',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zebras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('avg', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'zz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AffiliatedWith',
            fields=[
                ('physician', models.OneToOneField(db_column='physician', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='task1.physician')),
                ('primaryaffiliation', models.BooleanField()),
            ],
            options={
                'db_table': 'affiliated_with',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customercustomerdemo',
            fields=[
                ('customerid', models.OneToOneField(db_column='customerid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='task1.customers')),
            ],
            options={
                'db_table': 'customercustomerdemo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeeterritories',
            fields=[
                ('employeeid', models.OneToOneField(db_column='employeeid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='task1.employees')),
            ],
            options={
                'db_table': 'employeeterritories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnCall',
            fields=[
                ('nurse', models.OneToOneField(db_column='nurse', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='task1.nurse')),
                ('blockcode', models.IntegerField()),
                ('oncallstart', models.DateTimeField()),
                ('oncallend', models.DateTimeField()),
            ],
            options={
                'db_table': 'on_call',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('orderid', models.OneToOneField(db_column='orderid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='task1.orders')),
                ('unitprice', models.FloatField()),
                ('quantity', models.SmallIntegerField()),
                ('discount', models.FloatField()),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescribes',
            fields=[
                ('physician', models.OneToOneField(db_column='physician', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='task1.physician')),
                ('date', models.DateTimeField()),
                ('dose', models.TextField()),
            ],
            options={
                'db_table': 'prescribes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainedIn',
            fields=[
                ('physician', models.OneToOneField(db_column='physician', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='task1.physician')),
                ('certificationdate', models.DateField()),
                ('certificationexpires', models.DateField()),
            ],
            options={
                'db_table': 'trained_in',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Undergoes',
            fields=[
                ('patient', models.OneToOneField(db_column='patient', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='task1.patient')),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'undergoes',
                'managed': False,
            },
        ),
    ]
